name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Env Info
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}

      - name: Build Project
        run: vercel build --token=${{secrets.VERCEL_TOKEN}}

      - name: Deploy Project
        run: vercel deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}}

      - name: Get Deployment URL
        id: deployment
        run: echo "DEPLOYMENT_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --org ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }} --yes --scope my-team --env ENV_VAR_NAME=value | tail -1)" >> $GITHUB_ENV

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "🚀 Preview your changes: ${{ env.DEPLOYMENT_URL }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

